# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controls.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class ControlsUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(202, 439)

        # PARAMETERS
        self.label_parameters = QtWidgets.QLabel(Form)
        self.label_parameters.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label_parameters.setObjectName("label_parameters")

        # Isolation
        self.label_isolation = QtWidgets.QLabel(Form)
        self.label_isolation.setGeometry(QtCore.QRect(10, 40, 201, 51))
        self.label_isolation.setObjectName("label_isolation")

        self.slider_isolation = QtWidgets.QSlider(Form)
        self.slider_isolation.setGeometry(QtCore.QRect(10, 90, 161, 21))
        self.slider_isolation.setOrientation(QtCore.Qt.Horizontal)
        self.slider_isolation.setObjectName("slider_isolation")

        # Windows
        self.label_windows = QtWidgets.QLabel(Form)
        self.label_windows.setGeometry(QtCore.QRect(10, 140, 201, 51))
        self.label_windows.setObjectName("label_windows")

        self.slider_windows = QtWidgets.QSlider(Form)
        self.slider_windows.setGeometry(QtCore.QRect(10, 180, 161, 21))
        self.slider_windows.setOrientation(QtCore.Qt.Horizontal)
        self.slider_windows.setObjectName("slider_windows")

        # Orientation
        self.label_orientation = QtWidgets.QLabel(Form)
        self.label_orientation.setGeometry(QtCore.QRect(10, 230, 201, 51))
        self.label_orientation.setObjectName("label_orientation")

        self.dial_orientation = QtWidgets.QDial(Form)
        self.dial_orientation.setGeometry(QtCore.QRect(80, 310, 71, 71))
        self.dial_orientation.setObjectName("dial_orientation")

        self.label_north = QtWidgets.QLabel(Form)
        self.label_north.setGeometry(QtCore.QRect(80, 280, 71, 31))
        self.label_north.setAlignment(QtCore.Qt.AlignCenter)
        self.label_north.setObjectName("label_windows_2")

        self.label_south = QtWidgets.QLabel(Form)
        self.label_south.setGeometry(QtCore.QRect(80, 380, 71, 31))
        self.label_south.setAlignment(QtCore.Qt.AlignCenter)
        self.label_south.setObjectName("label_south")

        self.label_west = QtWidgets.QLabel(Form)
        self.label_west.setGeometry(QtCore.QRect(-10, 330, 81, 31))
        self.label_west.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_west.setObjectName("label_west")

        self.label_east = QtWidgets.QLabel(Form)
        self.label_east.setGeometry(QtCore.QRect(160, 330, 31, 31))
        self.label_east.setObjectName("label_east")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_parameters.setText(_translate("Form", "PARAMETRES"))
        self.label_isolation.setText(_translate("Form", "Largeur isolation"))
        self.label_windows.setText(_translate("Form", "Surface vitrée"))
        self.label_orientation.setText(_translate("Form", "Orientation"))
        self.label_north.setText(_translate("Form", "N"))
        self.label_south.setText(_translate("Form", "S"))
        self.label_west.setText(_translate("Form", "O"))
        self.label_east.setText(_translate("Form", "E"))


class ControlsWindow(QtWidgets.QMainWindow, ControlsUi):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.show()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    win = ControlsWindow()
    sys.exit(app.exec())