# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parameters.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import matplotlib
import numpy as np
from PyQt5 import QtCore, QtWidgets

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


from heatBalance import HeatBalance, HeatBalanceGraph


class MplCanvas(FigureCanvas):

    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111, ybound=(-40,40))
        super(MplCanvas, self).__init__(fig)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 60, 160, 21))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.label_3.setObjectName("label_3")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 120, 160, 21))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 101, 21))
        self.label_4.setObjectName("label_4")
        self.dial = QtWidgets.QDial(Form)
        self.dial.setGeometry(QtCore.QRect(50, 183, 71, 81))
        self.dial.setMaximum(359)
        self.dial.setPageStep(10)
        self.dial.setWrapping(True)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")

        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(100,0,900,600)
        layout = QtWidgets.QVBoxLayout(self.widget)

        self.canvas = HeatBalanceGraph(self.widget, width=10, height=8, dpi=100)
        self.canvas.setGeometry(QtCore.QRect(200, 10, 431, 251))
        heat_balance = HeatBalance()
        self.canvas.plot(heat_balance)
      

        #grid = np.linspace(-2, 2, 100)
        #self.canvas.xdata = grid
        #self.canvas.ydata = (grid ** 2)
        #self.canvas.show()
        self.window = 0
        self.isolation = 0
        self.orientation = 0

        #self.horizontalSlider.valueChanged['int'].connect(lambda state: self.update_plot(state,0))
        #self.horizontalSlider_2.valueChanged['int'].connect(lambda state: self.update_plot(state,1))
        #self.dial.valueChanged['int'].connect(lambda state: self.update_plot(state,2))



        layout.addWidget(self.canvas)

        #self.retranslateUi(Form)
        #QtCore.QMetaObject.connectSlotsByName(Form)

    # def update_plot(self,c,who):
    #     if who == 0:
    #         self.window = c
    #     if who == 1:
    #         self.isolation = c
    #     if who == 2:
    #         self.orientation = c

    #     self.canvas.ydata = (self.isolation*(self.canvas.xdata**2) + self.window) + np.exp(self.orientation/180)
    #     self.canvas.axes.cla()  # Clear the canvas.
    #     self.canvas.axes.plot(self.canvas.xdata, self.canvas.ydata, 'r')
    #     self.canvas.axes.set_ybound(-40, 40)
    #         # Trigger the canvas to update and redraw.
    #     self.canvas.draw()



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PARAMETERS"))
        self.label_2.setText(_translate("Form", "Windows"))
        self.label_3.setText(_translate("Form", "Isolation"))
        self.label_4.setText(_translate("Form", "Orientation"))


class Window(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.show()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    win = Window()
    sys.exit(app.exec())
